name: Deploy to production

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew shadowJar

      - name: Upload Bot to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          source: 'build/libs/SlimeBot.jar'
          target: '${{ secrets.PRODUCTION_WORK_DIR }}'
          strip_components: 2

      - name: Recreate Docker Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          script: cd ${{ secrets.WORK_DIR }} && ./rebuild.sh ${{ secrets.PRODUCTION_WORK_DIR }} SlimeBot slimebot 3737